<?xml version="1.0"?>
<package format="3">
  <name>rover_simulation</name>
  <version>0.1.0</version>
  <description>Lunar rover simulation package for ROS2 Jazzy + Gazebo Harmonic.</description>
  <maintainer email="monis@example.com">Monis</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>ros2launch</depend>
  <depend>robot_state_publisher</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>
  <depend>gazebo_ros_pkgs</depend>
  <depend>xacro</depend>
  <depend>rviz2</depend>
  <depend>tf2_ros</depend>
  <depend>nav2_common</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
