#!/usr/bin/env python3
"""
heightmap_to_collision_obj.py
-----------------------------
Generate a triangle-mesh collision surface that EXACTLY matches the visual
<heightmap> in lunar_terrain.world, so DART (which ignores <heightmap>
collision) has a drivable ground that lines up with what you see.

Visual heightmap in the world:
    <uri>heightmap.png</uri>  <size>150 150 10</size>  <pos>0 0 -5</pos>

Gazebo maps a 16-bit greyscale pixel p to:
    z_world = (p / 65535) * 10.0 - 5.0
    x_world in [-75, 75], y_world in [-75, 75]

Output: worlds/terrain_collision.obj  (129x129 grid -> 16641 verts / 32768 tris)
"""

import os

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
WORLDS = os.path.join(HERE, '..', 'src', 'rover_simulation', 'worlds')

PNG = os.path.join(WORLDS, 'heightmap.png')
OBJ = os.path.join(WORLDS, 'terrain_collision.obj')

WORLD_SIZE = 150.0      # <size> x/y
Z_SCALE = 10.0          # <size> z
Z_OFFSET = -5.0         # <pos> z
GRID_N = 129            # collision resolution (stride 8 over 1025)


def main():
    img = Image.open(PNG)
    arr = np.asarray(img).astype(np.float64)
    if arr.ndim == 3:
        arr = arr[:, :, 0]
    h, w = arr.shape
    print(f'heightmap.png: {w}x{h}, range {arr.min():.0f}..{arr.max():.0f}')

    # Downsample to GRID_N x GRID_N by picking evenly spaced rows/cols.
    ri = np.linspace(0, h - 1, GRID_N).round().astype(int)
    ci = np.linspace(0, w - 1, GRID_N).round().astype(int)
    sub = arr[np.ix_(ri, ci)]

    # 16-bit normalisation, matching Gazebo's <heightmap> mapping.
    z = (sub / 65535.0) * Z_SCALE + Z_OFFSET

    xs = np.linspace(-WORLD_SIZE / 2.0, WORLD_SIZE / 2.0, GRID_N)
    ys = np.linspace(-WORLD_SIZE / 2.0, WORLD_SIZE / 2.0, GRID_N)

    # Image row 0 is +Y (top of image) by Gazebo convention; flip so row index
    # increases with world +Y for a right-handed surface.
    z = np.flipud(z)

    print(f'collision mesh Z: {z.min():.3f} .. {z.max():.3f} m')
    ci_mid = GRID_N // 2
    print(f'Z at world origin (0,0): {z[ci_mid, ci_mid]:.3f} m')

    with open(OBJ, 'w') as f:
        f.write('# Terrain collision mesh — generated by heightmap_to_collision_obj.py\n')
        f.write('# Matches the visual <heightmap> in lunar_terrain.world. Do not edit.\n')
        f.write('o terrain_collision\n\n')
        for j in range(GRID_N):
            for i in range(GRID_N):
                f.write(f'v {xs[i]:.4f} {ys[j]:.4f} {z[j, i]:.4f}\n')
        f.write('\n')
        for j in range(GRID_N - 1):
            for i in range(GRID_N - 1):
                a = j * GRID_N + i + 1
                b = j * GRID_N + i + 2
                c = (j + 1) * GRID_N + i + 1
                d = (j + 1) * GRID_N + i + 2
                # two CCW triangles per quad
                f.write(f'f {a} {d} {b}\n')
                f.write(f'f {a} {c} {d}\n')

    kb = os.path.getsize(OBJ) / 1024.0
    print(f'wrote {OBJ}  ({kb:.0f} KB, {GRID_N * GRID_N} verts, {2 * (GRID_N - 1) ** 2} tris)')


if __name__ == '__main__':
    main()
